models/contact.py
from utils.db import db


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(50))
    email = db.Column(db.String(50))
    phone = db.Column(db.String(30))

    def __init__(self,fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
import imp
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

app.secret_key = 'mySecret'
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:root@localhost/contactsdb'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False 

SQLAlchemy(app)

app.register_blueprint(contacts)

routes/contacts.py
from msvcrt import kbhit
from flask import Blueprint, render_template, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__)

@contacts.route('/')
def index():
    contacts = Contact.query.all()
    return render_template('index.html', contacts=contacts)



@contacts.route('/new', methods=['POST'])
def add_contact():
    if request.method == 'POST':

        fullname = request.form['fullname']
        email = request.form['email']
        phone = request.form['phone']

        new_contact = Contact(fullname, email, phone)

        db.session.add(new_contact)
        db.session.commit()

        flash('Contact added successfully')

        return redirect(url_for('contacts.index'))
    
    


@contacts.route('/update/<id>', methods=['GET', 'POST'])
def update(id):
    contact = Contact.query.get(id)

    if request.method == 'POST':
        contact.fullname = request.form['fullname']
        contact.email = request.form['email']
        contact.phone = request.form['phone']

        db.session.commit()
        
        return redirect(url_for('contacts.index'))

    flash('Contact updated successfully')

    return render_template('update.html', contact=contact)



@contacts.route('/delete/<id>')
def delete(id):
   contact = Contact.query.get(id)
   db.session.delete(contact)
   db.session.commit()

   flash('Contact deleted successfully')

   return redirect(url_for('contacts.index'))



@contacts.route('/about')
def about():
    return render_template('about.html')

templates/about.html
<h1>About Us</h1>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In, voluptate quisquam? Eius explicabo facilis accusamus, sed impedit, optio voluptatem deserunt quia tempora iste perferendis, odio vel. Ut odio alias magnam!</p>

templates/index.html
{% with messages = get_flashed_messages() %}

    {% if messages %}
        {% for message in messages %}
            {{message}}
        {% endfor %}
    {% endif %}


{% endwith %}

<form action="/new" method="POST">

    <input type="text" name = "fullname" placeholder="Write your fullname">
    <input type="text" name = "email" placeholder="Write your email address">
    <input type="text" name = "phone" placeholder="Write your phone number">

    <button>Save</button>
</form>

<div>
    {% for contact in contacts %}

    <div>
        <h5>{{contact.fullname}}</h5>

        <div>
            <a href="{{ url_for('contacts.update', id = contact.id) }}">Update</a>
            <a href="{{ url_for('contacts.delete', id = contact.id) }}">Delete</a>
        </div>

        <p>{{contact.email}}</p>
        <p>{{contact.phone}}</p>

    </div>
    
    {% endfor %}
</div>

templates/update.html
<form action="/update/{{contact.id}}" method="POST">

    <input type="text" name = "fullname" placeholder="Write your fullname" value="{{contact.fullname}}">
    <input type="text" name = "email" placeholder="Write your email address" value="{{contact.email}}">
    <input type="text" name = "phone" placeholder="Write your phone number" value="{{contact.phone}}">

    <button>Save</button>
</form>